// Generated by CoffeeScript 1.6.3
(function() {
  var Status, StatusList, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Status = (function(_super) {
    __extends(Status, _super);

    function Status() {
      _ref = Status.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Status.prototype.templateName = 'my-status';

    Status.prototype.addMoney = function() {
      return this.money += 10;
    };

    Status.prototype.toggleShowAddMoney = function() {
      return this.showAddMoney = !this.showAddMoney;
    };

    return Status;

  })(Horn.View);

  StatusList = (function(_super) {
    __extends(StatusList, _super);

    function StatusList() {
      _ref1 = StatusList.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    StatusList.prototype.itemView = Status;

    StatusList.prototype.templateName = 'my-status-list';

    return StatusList;

  })(Horn.ListView);

  $(function() {
    window.list = new StatusList;
    list.attach('body');
    return list.update([
      {
        name: 1
      }, {
        name: 2
      }, {
        name: 3
      }
    ]);
  });

}).call(this);
